[package]
name = "iyes_progress"
version = "0.5.0"
edition = "2021"
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/IyesGames/iyes_progress"
keywords = ["game", "gamedev", "bevy"]
categories = ["game-engines"]
description = "Bevy plugin to help implement loading states"

[dependencies]
bevy_app = { git = "https://github.com/bevyengine/bevy", branch = "main" }
bevy_ecs = { git = "https://github.com/bevyengine/bevy", branch = "main" }
#bevy_ecs = "0.8"
#bevy_app = "0.8"
bevy_asset = { version = "0.8", optional = true }
bevy_utils = { version = "0.8", optional = true }

[dependencies.iyes_loopless]
version = "0.7"
optional = true
default-features = false
features = ["states", "app"]

[features]
assets = ["bevy_asset", "bevy_utils"]

[dev-dependencies]
bevy = "0.8"
iyes_loopless = "0.7"

[[example]]
name = "full"
required-features = ["iyes_loopless", "assets"]
